# Project: LQueue
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 代码和头文件/LQ/main.o 代码和头文件/LQ/LQueue.o
LINKOBJ  = 代码和头文件/LQ/main.o 代码和头文件/LQ/LQueue.o
LIBS     = -L"D:/dev/devc++/Dev-Cpp/MinGW64/lib" -L"D:/dev/devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/dev/devc++/Dev-Cpp/MinGW64/include" -I"D:/dev/devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/dev/devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/dev/devc++/Dev-Cpp/MinGW64/include" -I"D:/dev/devc++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/dev/devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/dev/devc++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = LQueue.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

代码和头文件/LQ/main.o: 代码和头文件/LQ/main.c
	$(CC) -c 代码和头文件/LQ/main.c -o 代码和头文件/LQ/main.o $(CFLAGS)

代码和头文件/LQ/LQueue.o: 代码和头文件/LQ/LQueue.c
	$(CC) -c 代码和头文件/LQ/LQueue.c -o 代码和头文件/LQ/LQueue.o $(CFLAGS)
